### ISSUE TITLE
Support `test/deps/build.jl`

### ISSUE THREAD

**Issue by rofinn** [StefanKarpinski/Pkg3.jl#5]
It would be nice to have a separate build.jl file just for running tests (e.g., pull down larger datasets just during testing).

**Comment by StefanKarpinski** [comment]
One of the ultimate design goals here is for packages to all be pure Julia with no build steps. Binary dependencies that require any building should be factored out into a yet-to-be-implemented "library" layer with their own versioning, upon which packages explicit depend. (A lot of how that works depends on the ongoing BinDeps2 work.) Ultimately, we should be able to load Julia packages without any checked out source tree – either by loading directly from a git repo with `libgit2` or from an archive like a `tar.gz/bz/xz` file. To that end, we need a general mechanism for packages that need non-source artifacts – this should be content-addressed both for security and verification (like we check cryptographic hashes of all dependencies when building Julia), and so that different versions can easily and automatically share cached copies of these artifacts. Test artifacts can use a more general artifact mechanism. I would imagine that there would be an `artifacts` directory in a depot where artifacts live, e.g. `~/.julia/artifacts/6f0e9def9a53ac13c219ef028d2f5ac7440aed641283bfdc041dc32cdf76c0e3`. If they're content-addressed they can be automatically shared between different packages and versions of packages. We would just need mechanisms for:

1. Indicating in package metadata that one depends on certain artifacts.
2. Requesting an artifact by some identifier.

The former is needed for garbage collection: when cleaning up artifacts, you need to know if there are any versions of packages that need any given artifact. The latter is needed so that you can use an artifact without hardcoding a location since the location will not be relative to the package source. It would make sense for the former to give a convenient unique name that can be used in the latter so that source files don't need some nasty hash value in them (which will change when the data is updated).

Straw man proposal – add this stanza to `Project.toml`:
```toml
[artifacts]
TestData1 = "6f0e9def9a53ac13c219ef028d2f5ac7440aed641283bfdc041dc32cdf76c0e3"
TestData2 = "158ee5ca9a8ae67f3513db4f96a850a3820177c70bb64d913d42aff517283dd6"
```
Then in some test file you can do this:
```jl
data1 = readcsv(artifact("TestData1"))
...
open(artifact("TestData2")) do io
    # do something with `io` to read from TestData2
end
```
Downloading artifacts could be eager or lazy, TBD.

**Comment by rofinn** [comment]
That seems like a reasonable approach. We're currently downloading and verifying test datasets in our build.jl files, but I think we'll be moving toward lazily downloading files in our test cases anyways.

**Comment by StefanKarpinski** [comment]
Oh, the other thing that's needed is a way to register artifacts and how to acquire them.
